// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpafoiivtwmcqgjvsgjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwYWZvaWl2dHdtY3FnanZzZ2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NDY2NTcsImV4cCI6MjA4NTIyMjY1N30.GXym_0e__jT1Qjk8DWu8ZqyitnW2FA-4RuQsWkCbzQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});